version: "3.8"

services:
  app:
    container_name: movie-api-container
    image: movie-api-container
    environment:
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000